### ISSUE TITLE
Galaxy 18.05 docker

### ISSUE THREAD

**Issue by mmiladi** [BackofenLab/GraphClust-2#63]
Running the 18.05 branch on Ubuntu 18.04 reports error:
```
Starting slurmd
Creating admin user admin@galaxy.org with key admin and password admin if not existing
Traceback (most recent call last):
  File "/usr/local/bin/create_galaxy_user.py", line 60, in <module>
    add_user(sa_session, security_agent, options.user, options.password, key=options.key, username=options.username)
  File "/usr/local/bin/create_galaxy_user.py", line 36, in add_user
    sa_session.flush()
  File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 866, in _emit_insert_statements
    execute(statement, params)
  File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/galaxy_venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "ix_api_keys_key"
DETAIL:  Key (key)=(admin) already exists.
 [SQL: 'INSERT INTO api_keys (create_time, user_id, key) VALUES (%(create_time)s, %(user_id)s, %(key)s) RETURNING api_keys.id'] [parameters: {'create_time': datetime.datetime(2018, 10, 12, 13, 31, 44, 786901), '
user_id': 2, 'key': 'admin'}] (Background on this error at: http://sqlalche.me/e/gkpj)
tail: unrecognized file system type 0x794c7630 for ‘/home/galaxy/logs/reports.log’. please report this to bug-coreutils@gnu.org. reverting to polling
tail: unrecognized file system type 0x794c7630 for ‘/home/galaxy/logs/slurmctld.log’. please report this to bug-coreutils@gnu.org. reverting to polling
==> /home/galaxy/logs/reports.log <==
galaxy.web.framework.base DEBUG 2018-10-12 13:31:18,273 Enabling 'tools' controller, class: Tools
galaxy.web.framework.base DEBUG 2018-10-12 13:31:18,273 Enabling 'root' controller, class: Report
galaxy.web.framework.base DEBUG 2018-10-12 13:31:18,274 Enabling 'home' controller, class: HomePage
galaxy.webapps.util DEBUG 2018-10-12 13:31:18,276 Enabling 'paste.httpexceptions' middleware
galaxy.webapps.util DEBUG 2018-10-12 13:31:18,276 Enabling 'RecursiveMiddleware' middleware
galaxy.webapps.util DEBUG 2018-10-12 13:31:18,280 Enabling 'ErrorMiddleware' middleware
galaxy.webapps.util DEBUG 2018-10-12 13:31:18,280 Enabling 'TransLogger' middleware
galaxy.webapps.util DEBUG 2018-10-12 13:31:18,281 Enabling 'XForwardedHostMiddleware' middleware
Starting server in PID 306.
serving on http://127.0.0.1:9001

==> /home/galaxy/logs/slurmctld.log <==
[2018-10-12T13:31:43.106] error: Could not open trigger state file /tmp/slurm/trigger_state: No such file or directory
[2018-10-12T13:31:43.106] error: NOTE: Trying backup state save file. Triggers may be lost!
[2018-10-12T13:31:43.106] No trigger state file (/tmp/slurm/trigger_state.old) to recover
[2018-10-12T13:31:43.106] error: Incomplete trigger data checkpoint file
[2018-10-12T13:31:43.106] read_slurm_conf: backup_controller not specified.
[2018-10-12T13:31:43.106] Reinitializing job accounting state
[2018-10-12T13:31:43.106] cons_res: select_p_reconfigure
[2018-10-12T13:31:43.106] cons_res: select_p_node_init
[2018-10-12T13:31:43.106] cons_res: preparing for 1 partitions
[2018-10-12T13:31:43.106] Running as primary controller

==> /home/galaxy/logs/slurmd.log <==
[2018-10-12T13:31:43.102] CPU frequency setting not configured for this node
[2018-10-12T13:31:43.103] slurmd version 2.6.5 started
[2018-10-12T13:31:43.104] slurmd started on Fri, 12 Oct 2018 13:31:43 +0000
[2018-10-12T13:31:43.104] CPUs=8 Boards=1 Sockets=8 Cores=1 Threads=1 Memory=16039 TmpDisk=99067 Uptime=4509

==> /home/galaxy/logs/uwsgi.log <==
galaxy.web.stack DEBUG 2018-10-12 13:31:18,330 [p:339,w:2,m:0] [MainThread] Calling postfork function: <function postfork_setup at 0x7fde2b6eab18>
galaxy.web.stack DEBUG 2018-10-12 13:31:18,330 [p:336,w:1,m:0] [MainThread] Calling postfork function: <function register at 0x7fde375eda28>
galaxy.queue_worker INFO 2018-10-12 13:31:18,330 [p:339,w:2,m:0] [MainThread] Binding and starting galaxy control worker for main.web.2
galaxy.web.stack DEBUG 2018-10-12 13:31:18,331 [p:336,w:1,m:0] [MainThread] Calling postfork function: <function postfork_setup at 0x7fde2b6eab18>
galaxy.queue_worker INFO 2018-10-12 13:31:18,331 [p:336,w:1,m:0] [MainThread] Binding and starting galaxy control worker for main.web.1
galaxy.web.stack INFO 2018-10-12 13:31:18,339 [p:336,w:1,m:0] [MainThread] Galaxy server instance 'main.web.1' is running
Starting server in PID 206.
serving on http://127.0.0.1:8080
serving on uwsgi://127.0.0.1:4001
galaxy.web.stack INFO 2018-10-12 13:31:18,343 [p:339,w:2,m:0] [MainThread] Galaxy server instance 'main.web.2' is running
tail: unrecognized file system type 0x794c7630 for ‘/home/galaxy/logs/slurmd.log’. please report this to bug-coreutils@gnu.org. reverting to polling
tail: unrecognized file system type 0x794c7630 for ‘/home/galaxy/logs/uwsgi.log’. please report this to bug-coreutils@gnu.org. reverting to polling

```

**Comment by mmiladi** [comment]
docker run mistake `-d -p 8080:80 -p 8021:21 -p 8022:22` was not passed to docker run.
